/*
Consider all integer combinations of a^b for 2 leq a leq 5 and 2 leq b leq 5:

2^2=4, 2^3=8, 2^4=16, 2^5=32
3^2=9, 3^3=27, 3^4=81, 3^5=243
4^2=16, 4^3=64, 4^4=256, 4^5=1024
5^2=25, 5^3=125, 5^4=625, 5^5=3125

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 leq a leq 100 and 2 leq b leq 100?
csc.exe C#.ex29.cs -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Numerics.dll"
*/
using System;
using System.Numerics;
using System.Collections.Generic;
using System.Linq;


class Ex29{
  static void Main(){
    int from=2, to=100;
    BigInteger bigint;
    string numstr;
    List<string> terms = new List<string>();

    for(int a=from; a<=to; a++){
      for(int b=from; b<=to; b++){
        bigint = BigInteger.Parse(a.ToString());
        bigint = BigInteger.Pow(bigint, b);
        numstr = bigint.ToString();
        terms.Add(numstr);
        //Console.WriteLine(numstr);
      }
    }

    HashSet<string> set = new HashSet<string>(terms);
    string[] distinct_terms = set.ToArray();
    Console.WriteLine(distinct_terms.Length);  // 9,183
  }
}
