%{
Consider all integer combinations of a^b for 2 leq a leq 5 and 2 leq b leq 5:

2^2=4, 2^3=8, 2^4=16, 2^5=32
3^2=9, 3^3=27, 3^4=81, 3^5=243
4^2=16, 4^3=64, 4^4=256, 4^5=1024
5^2=25, 5^3=125, 5^4=625, 5^5=3125

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 leq a leq 100 and 2 leq b leq 100?

We'll use the symbolic package https://octave.sourceforge.io/symbolic/function/vpa.html
pkg install -forge symbolic
%}

pkg load symbolic

rangea = 2:100;
rangeb = 2:100;

results = {};
counter = 1;

for a = rangea
  for b = rangeb
    result = vpa(a, 100) ^ b;
    results(counter) = char(result);
    counter += 1;
  end
end

results = unique(results);
disp(length(results))  # 9,183
