/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

public class JavaEx2 {

    public static void main(String[] args) {
      int temp, fibx = 1, fiby = 2;
      int sum = 2;  // only sum even valued terms
      int next_value;

      while(true) {
        next_value = fibx + fiby;
        temp = fiby;
        fiby = next_value;
        fibx = temp;

        if(next_value < 4000000){
          if(next_value % 2 == 0){  // only sum even valued terms
            sum = sum + next_value;
          }
        }else{
          break;
        }
      }

      System.out.println(sum); // 4,613,732
    }

}
