/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/
using System;
using System.Collections.Generic;


class Ex45{

  static long MAXN = (long)1e5;
  static long FIND_AFTER = 40755;


  static void Main(){
    List<long> tn = new List<long>();
    List<long> pn = new List<long>();
    List<long> hn = new List<long>();

    for(long n=1; n<=MAXN; n++){
      tn.Add(triangle(n));
      pn.Add(pentagonal(n));
      hn.Add(hexagonal(n));
    }

    long result = 0;
    long h;
    for(int i=0; i<=hn.Count; i++){
      h = hn[i];
      if(h <= FIND_AFTER){
        continue;
      }
      if(pn.Contains(h)){
        if(tn.Contains(h)){
          result = h;
          goto Found;
        }
      }
    }

    Found:
    Console.WriteLine(result);  // 1,533,776,805
  }


  static long triangle(long n){
    return n*(n+1)/2;
  }

  static long pentagonal(long n){
    return n*(3*n-1)/2;
  }

  static long hexagonal(long n){
    return  n*(2*n-1);
  }

}
