%{
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	  1, 3, 6, 10, 15, ...
Pentagonal	Pn=n(3n-1)/2	  1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	  1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
%}

MAXN = 1e5;
FIND_AFTER = 40755;

function retval = triangle(n)
  retval = n.*(n+1)/2;
end

function retval = pentagonal(n)
  retval = n.*(3.*n-1)/2;
end

function retval = hexagonal(n)
  retval = n.*(2.*n-1);
end


tn = triangle(1:MAXN);
pn = pentagonal(1:MAXN);
hn = hexagonal(1:MAXN);

overlap = and(ismember(hn, pn), ismember(hn, tn)); 
pos = find(overlap);
nums = hn(pos);  # all of the numbers that are overlapped

# find the first that is greater than FIND_AFTER
idx = find(nums > FIND_AFTER)(1);
result = nums(idx);

disp(result)  # 1,533,776,805
