--[[
Pentagonal numbers are generated by the formula, P(n) = n(3n-1)/2
The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their
sum and difference are pentagonal and D = abs(Pk - Pj) is minimised
what is the value of D?
--]]

function pentagonal_number(n)
  return n*(3*n-1)/2
end


function has_value(tbl, val)
  for k, v in pairs(tbl) do
    if v == val then
      return true
    end
  end
  return false
end


pentas = {}
for i=1,10 do
  pentas[i] = pentagonal_number(i);
end
--for k,v in pairs(pentas) do print(k,v) end

D = 0
n = #pentas
while D == 0 do
  n = n + 1
  penta = pentagonal_number(n)
  for k,p in pairs(pentas) do
    if has_value(pentas, penta-p) then
      if has_value(pentas, penta-2*p) then
        D = penta - 2*p
      end
    end
  end
  pentas[n] = penta
end

print(D)  -- 5,482,660
