%{
Pentagonal numbers are generated by the formula, P(n) = n(3n-1)/2
The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their
sum and difference are pentagonal and D = abs(Pk - Pj) is minimised
what is the value of D?
%}

function retval = pentagonal_number(n)
  retval = n.*(3.*n-1)/2;  
end

pentas = pentagonal_number(1:1e4);
[X, Y] = meshgrid(pentas, pentas);

sub = X - Y;
add = X + Y;
chk1 = ismember(sub, pentas);
chk2 = ismember(add, pentas);
cond = and(chk1, chk2);  # are both conditions met
pos = find(cond);        # collect the positions that are not zero
disp(sub(pos))  # 5,482,660
