%{
Pentagonal numbers are generated by the formula, P(n) = n(3n-1)/2
The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their
sum and difference are pentagonal and D = abs(Pk - Pj) is minimised
what is the value of D?
%}

function retval = pentagonal_number(n)
  retval = n.*(3.*n-1)/2;  
end

pentas = pentagonal_number(1:10);
D = 0;
n = length(pentas);
while D == 0
  n += 1;
  penta = pentagonal_number(n);
  pentas = [pentas, penta];
  for p = pentas
    condition1 = ((penta - p) == pentas);
    condition2 = ((pentas- 2*p) == pentas);
    condition = condition1 * condition2';
    if condition
      D = penta - 2*p;
      break;
    endif
  endfor
endwhile

disp(D)