
# Pentagonal numbers are generated by the formula, P(n) = n(3n-1)/2
# The first ten pentagonal numbers are:
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
# However, their difference, 70 - 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their
# sum and difference are pentagonal and D = abs(Pk - Pj) is minimised
# what is the value of D?

pentagonal_number <- function(n){
  return(n*(3*n-1)/2)
}

pentas <- sapply(1:10, pentagonal_number)
#print(pentas)  # [1]   1   5  12  22  35  51  70  92 117 145

D <- 0
n <- length(pentas)
while(D==0){
  n = n + 1
  penta <- pentagonal_number(n)
  for(i in 1:length(pentas)){
    p <- pentas[i]
    if((penta - p) %in% pentas){
      if((penta - 2*p) %in% pentas){
        D <- penta - 2*p
        break
      }
    }
  }
  pentas <- c(pentas, penta)
}

print(D)  # 5,482,660
